
name: Backend to Render

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-render.yml"
      - "render.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -s -X POST             -H "Accept: application/json"             -H "Authorization: Bearer ${RENDER_API_KEY}"             -H "Content-Type: application/json"             --data '{"serviceId":"'"${RENDER_SERVICE_ID}"'"}'             https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys
